global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['localhost:9100']
      - targets: ['111.88.240.79:9100']


  - job_name: 'instahelper_app'
    static_configs:
      - targets: ['127.0.0.1:8080']
      - targets: ['111.88.240.79:8080']

